# JVM
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

# Fabric Properties — https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties (change these together when renaming)
mod_version=1.0.3
maven_group=pl.peterwolf.echoesinink
archives_base_name=echoes-in-ink
mod_id=echoes_in_ink

# Dependencies
fabric_api_version=0.155.2+26.2
